### ISSUE TITLE
[help] Differences between nio.process.run and vim.fn.jobstart

### ISSUE THREAD

**Issue by benlubas** [nvim-neotest/nvim-nio#14]
I'm running into a weird issue where two commands are behaving differently if they're run with `vim.fn.jobstart` or `nio.process.run`.

Specifically `dvipng` can't produce transparent images with `process.run`, but can with `jobstart`.

```lua
nio.process.run({
    cmd = "dvipng",
    args = {
        "-D",
        module.config.public.dpi,
        "-T tight",
        "-bg Transparent",
        "-fg 'cmyk 0.00 0.04 0.21 0.02'",
        "-o",
        png_result,
        ("%s.dvi"):format(document_name),
    },
})
-- vs:
nio.fn.jobstart(
    "dvipng -D "
    .. tostring(module.config.public.dpi)
    .. " -T tight -bg Transparent -fg 'cmyk 0.00 0.04 0.21 0.02' -o "
    .. png_result
    .. " "
    .. document_name
    .. ".dvi",
    { cwd = cwd }
)
```

![image](https://github.com/nvim-neotest/nvim-nio/assets/56943754/15e70ef5-3cb6-4025-8d0f-f367b42e8bee)

vs:

![image](https://github.com/nvim-neotest/nvim-nio/assets/56943754/d82cf8f3-d78e-4d2e-9c04-70f2dd091ea0)

---

Seems like job start does something special with the environment that it runs things in. Is there a way to mimic this with `process.run` or should I just use `nio.fn.jobstart`? if you have a concrete explanation for what's happening that'd be great too, I'd not been able to find anyone that has this problem with `dvipng` (but it's also probably a niche usecase).

**Comment by rcarriga** [comment]
I'm not familiar with `dvipng` but you're not correctly passing the arguments. They should all be separate in the array like this
```lua
nio.process.run({
  cmd = "dvipng",
  args = {
    "-D",
    module.config.public.dpi,
    "-T",
    "tight",
    "-bg",
    "Transparent",
    "-fg",
    "cmyk 0.00 0.04 0.21 0.02",
    "-o",
    png_result,
    ("%s.dvi"):format(document_name),
  },
})
```
It is not like a shell so you don't need to quote the arguments as you had with `cmyk 0.00 0.04 0.21 0.02`

**Comment by benlubas** [comment]
That works, thank you. I should read the docs a little closer next time
