### ISSUE TITLE
Deprecation warnings in v0.10 and v11 nightlies

### ISSUE THREAD

**Issue by cwebster2** [nvim-neotest/nvim-nio#17]
**NeoVim Version**
`NVIM v0.11.0-dev-4+ga66424617` 

**Describe the bug**
Deprecation warning for vim.tbl_flatten

**To Reproduce**
Start nvim with nvim-nio enabled

```
vim.tbl_flatten is deprecated, use vim.iter(…):flatten():totable() instead. :help deprecated
Feature will be removed in Nvim 0.12
stack traceback:
        vim/shared.lua: in function 'tbl_flatten'
        ...casey/.local/share/nvim/lazy/nvim-nio/lua/nio/logger.lua:39: in function 'path_join'
```

https://github.com/nvim-neotest/nvim-nio/blob/8765cbc4d0c629c8158a5341e1b4305fd93c3a90/lua/nio/logger.lua#L39

**Comment by rcarriga** [comment]
Closed by #18
