### ISSUE TITLE
[BUG] Luarocks package not updated since 1.2.0-1

### ISSUE THREAD

**Issue by pysan3** [nvim-neotest/nvim-nio#6]
**Describe the bug**

[nvim-nio](https://luarocks.org/modules/neotest/nvim-nio) published to luarocks has not received an update since [1.2.0-1](https://luarocks.org/modules/neotest/nvim-nio/1.2.0-1).

The latest tag is 1.4.0 on GitHub with `nio.current_task()` added which I need for my plugin.

I'd be more than happy if you could update the luarocks version as well.

**Additional context**
FYI, there's a GitHub action to publish to luarocks which might be useful for you.

- https://github.com/nvim-neorocks/luarocks-tag-release
- Tutorial: https://github.com/nvim-neorocks/sample-luarocks-plugin

**Comment by rcarriga** [comment]
I do use the workflow already but for some reason it wasn't releasing automatically, I'll have to keep an eye on it. For now anyway I've published the latest version

**Comment by pysan3** [comment]
I believe it is caused by this issue.

https://github.com/nvim-neorocks/sample-luarocks-plugin/issues/1

Previously, release to luarocks action only ran on a push to a tag, which is auto created by release-action. 
After `GITHUB_TOKEN` is used once, the chain of actions will stop there as stated here: https://github.com/google-github-actions/release-please-action#github-credentials, so you need to set a separate access token in release-please that you manually created via user settings in order to complete the chain of actions.
