### ISSUE TITLE
[DOC] Please make separate (sub) section for each functionality.

### ISSUE THREAD

**Issue by pysan3** [nvim-neotest/nvim-nio#8]
In the current README, all explanation of `nio.*` classes are provided as simple paragraphs.

As per the limitation on GitHub, only sections are provided with a link (eg https://github.com/nvim-neotest/nvim-nio#usage ).

I would appreciate if it would be possible to make the feature paragraphs their own distinct sections, such as `### nio.control`.

Thanks in advance ;)

**Comment by pysan3** [comment]
@rcarriga 

Unrelated but,

How should I describe to be inside a `nio.run`?

```lua
nio.run(function ()
  -- inside a <???>
  -- - an asynchronous environment?
  -- - a nio task?
  -- - a nio job?
  -- - a nio environment?
  -- - a nio run?
end)
```

**Comment by rcarriga** [comment]
Good question :sweat_smile: I refer to them as "async contexts" in the [docs](https://github.com/nvim-neotest/nvim-nio/blob/a5818ac31c0ec1b3f8ab87c9d00d7d6d35eba106/doc/nio.txt#L26-L27) and [error messages](https://github.com/nvim-neotest/nvim-nio/blob/a5818ac31c0ec1b3f8ab87c9d00d7d6d35eba106/lua/nio/tasks.lua#L193).

**Comment by pysan3** [comment]
Ah, nice. Thanks ;)
